//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiosMoneyApp.Servicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BiosMoneyApp.Servicio.Gerente))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BiosMoneyApp.Servicio.Cajero))]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ci {
            get {
                return this.CiField;
            }
            set {
                if ((this.CiField.Equals(value) != true)) {
                    this.CiField = value;
                    this.RaisePropertyChanged("Ci");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomCompleto {
            get {
                return this.NomCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomCompletoField, value) != true)) {
                    this.NomCompletoField = value;
                    this.RaisePropertyChanged("NomCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu {
            get {
                return this.UsuField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuField, value) != true)) {
                    this.UsuField = value;
                    this.RaisePropertyChanged("Usu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gerente", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Gerente : BiosMoneyApp.Servicio.Usuario {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cajero", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Cajero : BiosMoneyApp.Servicio.Usuario {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraInicioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraFin {
            get {
                return this.HoraFinField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraFinField, value) != true)) {
                    this.HoraFinField = value;
                    this.RaisePropertyChanged("HoraFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraInicio {
            get {
                return this.HoraInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraInicioField, value) != true)) {
                    this.HoraInicioField = value;
                    this.RaisePropertyChanged("HoraInicio");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empresa", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Empresa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirFiscalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirFiscal {
            get {
                return this.DirFiscalField;
            }
            set {
                if ((object.ReferenceEquals(this.DirFiscalField, value) != true)) {
                    this.DirFiscalField = value;
                    this.RaisePropertyChanged("DirFiscal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Rut {
            get {
                return this.RutField;
            }
            set {
                if ((this.RutField.Equals(value) != true)) {
                    this.RutField = value;
                    this.RaisePropertyChanged("Rut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Tel {
            get {
                return this.TelField;
            }
            set {
                if ((this.TelField.Equals(value) != true)) {
                    this.TelField = value;
                    this.RaisePropertyChanged("Tel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contrato", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Contrato : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BiosMoneyApp.Servicio.Empresa EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomContratoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodContrato {
            get {
                return this.CodContratoField;
            }
            set {
                if ((this.CodContratoField.Equals(value) != true)) {
                    this.CodContratoField = value;
                    this.RaisePropertyChanged("CodContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BiosMoneyApp.Servicio.Empresa Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomContrato {
            get {
                return this.NomContratoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomContratoField, value) != true)) {
                    this.NomContratoField = value;
                    this.RaisePropertyChanged("NomContrato");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pago", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Pago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BiosMoneyApp.Servicio.Usuario CajeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BiosMoneyApp.Servicio.LineaPago[] LineasPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumeroInternoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BiosMoneyApp.Servicio.Usuario Cajero {
            get {
                return this.CajeroField;
            }
            set {
                if ((object.ReferenceEquals(this.CajeroField, value) != true)) {
                    this.CajeroField = value;
                    this.RaisePropertyChanged("Cajero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BiosMoneyApp.Servicio.LineaPago[] LineasPago {
            get {
                return this.LineasPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.LineasPagoField, value) != true)) {
                    this.LineasPagoField = value;
                    this.RaisePropertyChanged("LineasPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumeroInterno {
            get {
                return this.NumeroInternoField;
            }
            set {
                if ((this.NumeroInternoField.Equals(value) != true)) {
                    this.NumeroInternoField = value;
                    this.RaisePropertyChanged("NumeroInterno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LineaPago", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class LineaPago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BiosMoneyApp.Servicio.Contrato ContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MontoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodContrato {
            get {
                return this.CodContratoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodContratoField, value) != true)) {
                    this.CodContratoField = value;
                    this.RaisePropertyChanged("CodContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoCliente {
            get {
                return this.CodigoClienteField;
            }
            set {
                if ((this.CodigoClienteField.Equals(value) != true)) {
                    this.CodigoClienteField = value;
                    this.RaisePropertyChanged("CodigoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BiosMoneyApp.Servicio.Contrato Contrato {
            get {
                return this.ContratoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContratoField, value) != true)) {
                    this.ContratoField = value;
                    this.RaisePropertyChanged("Contrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaVencimiento {
            get {
                return this.FechaVencimientoField;
            }
            set {
                if ((this.FechaVencimientoField.Equals(value) != true)) {
                    this.FechaVencimientoField = value;
                    this.RaisePropertyChanged("FechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servicio.IMiServicio")]
    public interface IMiServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/Logueo", ReplyAction="http://tempuri.org/IMiServicio/LogueoResponse")]
        BiosMoneyApp.Servicio.Usuario Logueo(string usuario, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/Logueo", ReplyAction="http://tempuri.org/IMiServicio/LogueoResponse")]
        System.Threading.Tasks.Task<BiosMoneyApp.Servicio.Usuario> LogueoAsync(string usuario, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/Alta", ReplyAction="http://tempuri.org/IMiServicio/AltaResponse")]
        void Alta(BiosMoneyApp.Servicio.Usuario usuario, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/Alta", ReplyAction="http://tempuri.org/IMiServicio/AltaResponse")]
        System.Threading.Tasks.Task AltaAsync(BiosMoneyApp.Servicio.Usuario usuario, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ListarGerentes", ReplyAction="http://tempuri.org/IMiServicio/ListarGerentesResponse")]
        BiosMoneyApp.Servicio.Gerente[] ListarGerentes(BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ListarGerentes", ReplyAction="http://tempuri.org/IMiServicio/ListarGerentesResponse")]
        System.Threading.Tasks.Task<BiosMoneyApp.Servicio.Gerente[]> ListarGerentesAsync(BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ModificarClave", ReplyAction="http://tempuri.org/IMiServicio/ModificarClaveResponse")]
        void ModificarClave(BiosMoneyApp.Servicio.Usuario usuario, string clave1, string clave2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ModificarClave", ReplyAction="http://tempuri.org/IMiServicio/ModificarClaveResponse")]
        System.Threading.Tasks.Task ModificarClaveAsync(BiosMoneyApp.Servicio.Usuario usuario, string clave1, string clave2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/BajaCajero", ReplyAction="http://tempuri.org/IMiServicio/BajaCajeroResponse")]
        void BajaCajero(BiosMoneyApp.Servicio.Usuario cajero, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/BajaCajero", ReplyAction="http://tempuri.org/IMiServicio/BajaCajeroResponse")]
        System.Threading.Tasks.Task BajaCajeroAsync(BiosMoneyApp.Servicio.Usuario cajero, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/BuscarCajero", ReplyAction="http://tempuri.org/IMiServicio/BuscarCajeroResponse")]
        BiosMoneyApp.Servicio.Cajero BuscarCajero(int Ci, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/BuscarCajero", ReplyAction="http://tempuri.org/IMiServicio/BuscarCajeroResponse")]
        System.Threading.Tasks.Task<BiosMoneyApp.Servicio.Cajero> BuscarCajeroAsync(int Ci, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/Modificar", ReplyAction="http://tempuri.org/IMiServicio/ModificarResponse")]
        void Modificar(BiosMoneyApp.Servicio.Usuario cajero, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/Modificar", ReplyAction="http://tempuri.org/IMiServicio/ModificarResponse")]
        System.Threading.Tasks.Task ModificarAsync(BiosMoneyApp.Servicio.Usuario cajero, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ListarCajeros", ReplyAction="http://tempuri.org/IMiServicio/ListarCajerosResponse")]
        BiosMoneyApp.Servicio.Cajero[] ListarCajeros(BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ListarCajeros", ReplyAction="http://tempuri.org/IMiServicio/ListarCajerosResponse")]
        System.Threading.Tasks.Task<BiosMoneyApp.Servicio.Cajero[]> ListarCajerosAsync(BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ActualizarHorasExtra", ReplyAction="http://tempuri.org/IMiServicio/ActualizarHorasExtraResponse")]
        void ActualizarHorasExtra(BiosMoneyApp.Servicio.Cajero _cajero, System.DateTime _fecha, int _minutosExtra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ActualizarHorasExtra", ReplyAction="http://tempuri.org/IMiServicio/ActualizarHorasExtraResponse")]
        System.Threading.Tasks.Task ActualizarHorasExtraAsync(BiosMoneyApp.Servicio.Cajero _cajero, System.DateTime _fecha, int _minutosExtra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/AltaEmpresa", ReplyAction="http://tempuri.org/IMiServicio/AltaEmpresaResponse")]
        void AltaEmpresa(BiosMoneyApp.Servicio.Empresa empresa, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/AltaEmpresa", ReplyAction="http://tempuri.org/IMiServicio/AltaEmpresaResponse")]
        System.Threading.Tasks.Task AltaEmpresaAsync(BiosMoneyApp.Servicio.Empresa empresa, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ModEmpresa", ReplyAction="http://tempuri.org/IMiServicio/ModEmpresaResponse")]
        void ModEmpresa(BiosMoneyApp.Servicio.Empresa empresa, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ModEmpresa", ReplyAction="http://tempuri.org/IMiServicio/ModEmpresaResponse")]
        System.Threading.Tasks.Task ModEmpresaAsync(BiosMoneyApp.Servicio.Empresa empresa, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/BajaEmpresa", ReplyAction="http://tempuri.org/IMiServicio/BajaEmpresaResponse")]
        void BajaEmpresa(BiosMoneyApp.Servicio.Empresa empresa, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/BajaEmpresa", ReplyAction="http://tempuri.org/IMiServicio/BajaEmpresaResponse")]
        System.Threading.Tasks.Task BajaEmpresaAsync(BiosMoneyApp.Servicio.Empresa empresa, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/BuscarEmpresa", ReplyAction="http://tempuri.org/IMiServicio/BuscarEmpresaResponse")]
        BiosMoneyApp.Servicio.Empresa BuscarEmpresa(int codigo, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/BuscarEmpresa", ReplyAction="http://tempuri.org/IMiServicio/BuscarEmpresaResponse")]
        System.Threading.Tasks.Task<BiosMoneyApp.Servicio.Empresa> BuscarEmpresaAsync(int codigo, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ListarEmpresa", ReplyAction="http://tempuri.org/IMiServicio/ListarEmpresaResponse")]
        BiosMoneyApp.Servicio.Empresa[] ListarEmpresa(BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ListarEmpresa", ReplyAction="http://tempuri.org/IMiServicio/ListarEmpresaResponse")]
        System.Threading.Tasks.Task<BiosMoneyApp.Servicio.Empresa[]> ListarEmpresaAsync(BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/AltaContrato", ReplyAction="http://tempuri.org/IMiServicio/AltaContratoResponse")]
        void AltaContrato(BiosMoneyApp.Servicio.Contrato contrato, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/AltaContrato", ReplyAction="http://tempuri.org/IMiServicio/AltaContratoResponse")]
        System.Threading.Tasks.Task AltaContratoAsync(BiosMoneyApp.Servicio.Contrato contrato, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/BajaContrato", ReplyAction="http://tempuri.org/IMiServicio/BajaContratoResponse")]
        void BajaContrato(BiosMoneyApp.Servicio.Contrato contrato, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/BajaContrato", ReplyAction="http://tempuri.org/IMiServicio/BajaContratoResponse")]
        System.Threading.Tasks.Task BajaContratoAsync(BiosMoneyApp.Servicio.Contrato contrato, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ModContrato", ReplyAction="http://tempuri.org/IMiServicio/ModContratoResponse")]
        void ModContrato(BiosMoneyApp.Servicio.Contrato contrato, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ModContrato", ReplyAction="http://tempuri.org/IMiServicio/ModContratoResponse")]
        System.Threading.Tasks.Task ModContratoAsync(BiosMoneyApp.Servicio.Contrato contrato, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/BuscarContrato", ReplyAction="http://tempuri.org/IMiServicio/BuscarContratoResponse")]
        BiosMoneyApp.Servicio.Contrato BuscarContrato(int codigoEmpresa, int codTipo, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/BuscarContrato", ReplyAction="http://tempuri.org/IMiServicio/BuscarContratoResponse")]
        System.Threading.Tasks.Task<BiosMoneyApp.Servicio.Contrato> BuscarContratoAsync(int codigoEmpresa, int codTipo, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ListarContrato", ReplyAction="http://tempuri.org/IMiServicio/ListarContratoResponse")]
        BiosMoneyApp.Servicio.Contrato[] ListarContrato(BiosMoneyApp.Servicio.Empresa empresa, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ListarContrato", ReplyAction="http://tempuri.org/IMiServicio/ListarContratoResponse")]
        System.Threading.Tasks.Task<BiosMoneyApp.Servicio.Contrato[]> ListarContratoAsync(BiosMoneyApp.Servicio.Empresa empresa, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/GenerarXMLContratos", ReplyAction="http://tempuri.org/IMiServicio/GenerarXMLContratosResponse")]
        string GenerarXMLContratos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/GenerarXMLContratos", ReplyAction="http://tempuri.org/IMiServicio/GenerarXMLContratosResponse")]
        System.Threading.Tasks.Task<string> GenerarXMLContratosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ChequearFacturaPaga", ReplyAction="http://tempuri.org/IMiServicio/ChequearFacturaPagaResponse")]
        System.DateTime ChequearFacturaPaga(string factura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ChequearFacturaPaga", ReplyAction="http://tempuri.org/IMiServicio/ChequearFacturaPagaResponse")]
        System.Threading.Tasks.Task<System.DateTime> ChequearFacturaPagaAsync(string factura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/AltaPago", ReplyAction="http://tempuri.org/IMiServicio/AltaPagoResponse")]
        void AltaPago(BiosMoneyApp.Servicio.Pago pago, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/AltaPago", ReplyAction="http://tempuri.org/IMiServicio/AltaPagoResponse")]
        System.Threading.Tasks.Task AltaPagoAsync(BiosMoneyApp.Servicio.Pago pago, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ListarPagos", ReplyAction="http://tempuri.org/IMiServicio/ListarPagosResponse")]
        BiosMoneyApp.Servicio.Pago[] ListarPagos(BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ListarPagos", ReplyAction="http://tempuri.org/IMiServicio/ListarPagosResponse")]
        System.Threading.Tasks.Task<BiosMoneyApp.Servicio.Pago[]> ListarPagosAsync(BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ListarFacturas", ReplyAction="http://tempuri.org/IMiServicio/ListarFacturasResponse")]
        BiosMoneyApp.Servicio.LineaPago[] ListarFacturas(int _NumeroInterno, BiosMoneyApp.Servicio.Usuario logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ListarFacturas", ReplyAction="http://tempuri.org/IMiServicio/ListarFacturasResponse")]
        System.Threading.Tasks.Task<BiosMoneyApp.Servicio.LineaPago[]> ListarFacturasAsync(int _NumeroInterno, BiosMoneyApp.Servicio.Usuario logueo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMiServicioChannel : BiosMoneyApp.Servicio.IMiServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MiServicioClient : System.ServiceModel.ClientBase<BiosMoneyApp.Servicio.IMiServicio>, BiosMoneyApp.Servicio.IMiServicio {
        
        public MiServicioClient() {
        }
        
        public MiServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MiServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BiosMoneyApp.Servicio.Usuario Logueo(string usuario, string clave) {
            return base.Channel.Logueo(usuario, clave);
        }
        
        public System.Threading.Tasks.Task<BiosMoneyApp.Servicio.Usuario> LogueoAsync(string usuario, string clave) {
            return base.Channel.LogueoAsync(usuario, clave);
        }
        
        public void Alta(BiosMoneyApp.Servicio.Usuario usuario, BiosMoneyApp.Servicio.Usuario logueo) {
            base.Channel.Alta(usuario, logueo);
        }
        
        public System.Threading.Tasks.Task AltaAsync(BiosMoneyApp.Servicio.Usuario usuario, BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.AltaAsync(usuario, logueo);
        }
        
        public BiosMoneyApp.Servicio.Gerente[] ListarGerentes(BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.ListarGerentes(logueo);
        }
        
        public System.Threading.Tasks.Task<BiosMoneyApp.Servicio.Gerente[]> ListarGerentesAsync(BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.ListarGerentesAsync(logueo);
        }
        
        public void ModificarClave(BiosMoneyApp.Servicio.Usuario usuario, string clave1, string clave2) {
            base.Channel.ModificarClave(usuario, clave1, clave2);
        }
        
        public System.Threading.Tasks.Task ModificarClaveAsync(BiosMoneyApp.Servicio.Usuario usuario, string clave1, string clave2) {
            return base.Channel.ModificarClaveAsync(usuario, clave1, clave2);
        }
        
        public void BajaCajero(BiosMoneyApp.Servicio.Usuario cajero, BiosMoneyApp.Servicio.Usuario logueo) {
            base.Channel.BajaCajero(cajero, logueo);
        }
        
        public System.Threading.Tasks.Task BajaCajeroAsync(BiosMoneyApp.Servicio.Usuario cajero, BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.BajaCajeroAsync(cajero, logueo);
        }
        
        public BiosMoneyApp.Servicio.Cajero BuscarCajero(int Ci, BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.BuscarCajero(Ci, logueo);
        }
        
        public System.Threading.Tasks.Task<BiosMoneyApp.Servicio.Cajero> BuscarCajeroAsync(int Ci, BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.BuscarCajeroAsync(Ci, logueo);
        }
        
        public void Modificar(BiosMoneyApp.Servicio.Usuario cajero, BiosMoneyApp.Servicio.Usuario logueo) {
            base.Channel.Modificar(cajero, logueo);
        }
        
        public System.Threading.Tasks.Task ModificarAsync(BiosMoneyApp.Servicio.Usuario cajero, BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.ModificarAsync(cajero, logueo);
        }
        
        public BiosMoneyApp.Servicio.Cajero[] ListarCajeros(BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.ListarCajeros(logueo);
        }
        
        public System.Threading.Tasks.Task<BiosMoneyApp.Servicio.Cajero[]> ListarCajerosAsync(BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.ListarCajerosAsync(logueo);
        }
        
        public void ActualizarHorasExtra(BiosMoneyApp.Servicio.Cajero _cajero, System.DateTime _fecha, int _minutosExtra) {
            base.Channel.ActualizarHorasExtra(_cajero, _fecha, _minutosExtra);
        }
        
        public System.Threading.Tasks.Task ActualizarHorasExtraAsync(BiosMoneyApp.Servicio.Cajero _cajero, System.DateTime _fecha, int _minutosExtra) {
            return base.Channel.ActualizarHorasExtraAsync(_cajero, _fecha, _minutosExtra);
        }
        
        public void AltaEmpresa(BiosMoneyApp.Servicio.Empresa empresa, BiosMoneyApp.Servicio.Usuario logueo) {
            base.Channel.AltaEmpresa(empresa, logueo);
        }
        
        public System.Threading.Tasks.Task AltaEmpresaAsync(BiosMoneyApp.Servicio.Empresa empresa, BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.AltaEmpresaAsync(empresa, logueo);
        }
        
        public void ModEmpresa(BiosMoneyApp.Servicio.Empresa empresa, BiosMoneyApp.Servicio.Usuario logueo) {
            base.Channel.ModEmpresa(empresa, logueo);
        }
        
        public System.Threading.Tasks.Task ModEmpresaAsync(BiosMoneyApp.Servicio.Empresa empresa, BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.ModEmpresaAsync(empresa, logueo);
        }
        
        public void BajaEmpresa(BiosMoneyApp.Servicio.Empresa empresa, BiosMoneyApp.Servicio.Usuario logueo) {
            base.Channel.BajaEmpresa(empresa, logueo);
        }
        
        public System.Threading.Tasks.Task BajaEmpresaAsync(BiosMoneyApp.Servicio.Empresa empresa, BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.BajaEmpresaAsync(empresa, logueo);
        }
        
        public BiosMoneyApp.Servicio.Empresa BuscarEmpresa(int codigo, BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.BuscarEmpresa(codigo, logueo);
        }
        
        public System.Threading.Tasks.Task<BiosMoneyApp.Servicio.Empresa> BuscarEmpresaAsync(int codigo, BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.BuscarEmpresaAsync(codigo, logueo);
        }
        
        public BiosMoneyApp.Servicio.Empresa[] ListarEmpresa(BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.ListarEmpresa(logueo);
        }
        
        public System.Threading.Tasks.Task<BiosMoneyApp.Servicio.Empresa[]> ListarEmpresaAsync(BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.ListarEmpresaAsync(logueo);
        }
        
        public void AltaContrato(BiosMoneyApp.Servicio.Contrato contrato, BiosMoneyApp.Servicio.Usuario logueo) {
            base.Channel.AltaContrato(contrato, logueo);
        }
        
        public System.Threading.Tasks.Task AltaContratoAsync(BiosMoneyApp.Servicio.Contrato contrato, BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.AltaContratoAsync(contrato, logueo);
        }
        
        public void BajaContrato(BiosMoneyApp.Servicio.Contrato contrato, BiosMoneyApp.Servicio.Usuario logueo) {
            base.Channel.BajaContrato(contrato, logueo);
        }
        
        public System.Threading.Tasks.Task BajaContratoAsync(BiosMoneyApp.Servicio.Contrato contrato, BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.BajaContratoAsync(contrato, logueo);
        }
        
        public void ModContrato(BiosMoneyApp.Servicio.Contrato contrato, BiosMoneyApp.Servicio.Usuario logueo) {
            base.Channel.ModContrato(contrato, logueo);
        }
        
        public System.Threading.Tasks.Task ModContratoAsync(BiosMoneyApp.Servicio.Contrato contrato, BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.ModContratoAsync(contrato, logueo);
        }
        
        public BiosMoneyApp.Servicio.Contrato BuscarContrato(int codigoEmpresa, int codTipo, BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.BuscarContrato(codigoEmpresa, codTipo, logueo);
        }
        
        public System.Threading.Tasks.Task<BiosMoneyApp.Servicio.Contrato> BuscarContratoAsync(int codigoEmpresa, int codTipo, BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.BuscarContratoAsync(codigoEmpresa, codTipo, logueo);
        }
        
        public BiosMoneyApp.Servicio.Contrato[] ListarContrato(BiosMoneyApp.Servicio.Empresa empresa, BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.ListarContrato(empresa, logueo);
        }
        
        public System.Threading.Tasks.Task<BiosMoneyApp.Servicio.Contrato[]> ListarContratoAsync(BiosMoneyApp.Servicio.Empresa empresa, BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.ListarContratoAsync(empresa, logueo);
        }
        
        public string GenerarXMLContratos() {
            return base.Channel.GenerarXMLContratos();
        }
        
        public System.Threading.Tasks.Task<string> GenerarXMLContratosAsync() {
            return base.Channel.GenerarXMLContratosAsync();
        }
        
        public System.DateTime ChequearFacturaPaga(string factura) {
            return base.Channel.ChequearFacturaPaga(factura);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> ChequearFacturaPagaAsync(string factura) {
            return base.Channel.ChequearFacturaPagaAsync(factura);
        }
        
        public void AltaPago(BiosMoneyApp.Servicio.Pago pago, BiosMoneyApp.Servicio.Usuario logueo) {
            base.Channel.AltaPago(pago, logueo);
        }
        
        public System.Threading.Tasks.Task AltaPagoAsync(BiosMoneyApp.Servicio.Pago pago, BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.AltaPagoAsync(pago, logueo);
        }
        
        public BiosMoneyApp.Servicio.Pago[] ListarPagos(BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.ListarPagos(logueo);
        }
        
        public System.Threading.Tasks.Task<BiosMoneyApp.Servicio.Pago[]> ListarPagosAsync(BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.ListarPagosAsync(logueo);
        }
        
        public BiosMoneyApp.Servicio.LineaPago[] ListarFacturas(int _NumeroInterno, BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.ListarFacturas(_NumeroInterno, logueo);
        }
        
        public System.Threading.Tasks.Task<BiosMoneyApp.Servicio.LineaPago[]> ListarFacturasAsync(int _NumeroInterno, BiosMoneyApp.Servicio.Usuario logueo) {
            return base.Channel.ListarFacturasAsync(_NumeroInterno, logueo);
        }
    }
}
